[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "monitor"
version = "1.0.0"
description = "A modular LLM Command-line Assistant"
authors = [
    { name = "Rodney Degracia", email = "rdegraci@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyyaml==6.0.2",
    "dotenv==0.9.9",
    "colored==2.3.0",
    "litellm==1.73.0",
    "prompt_toolkit==3.0.51",
    "pygments==2.19.1",
    "mcp==1.9.0",
    "tavily-python==0.7.2",
    "pandas==2.2.3",
    "scikit-learn==1.6.1",
    "redis==6.1.0",
    "openai-whisper",
    "pyaudio==0.2.14",
    "graphviz==0.20.3",
    "ollama==0.4.8",
    "duckdb==1.2.2",
    "GitPython==3.1.44",
    "tiktoken==0.9.0",
    "anthropic==0.54.0",
    "flask==3.1.1",
    "coqui-tts==0.27.0",
    "openai==1.101.0"
]

[project.scripts]
monitor = "monitor.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
monitor = [
    "app.yaml",
    "preferences.prompt",
    "public_commands.json",
    "macros.json",
    "model_config.json"
]